RDKBACCL-1619 : Internittenlty mysqld service is failing.
Reason For Change: mysqld service keep on starting, As it is in Activating State only.
Test Procedure: mysqld service should be up and running.
Risks: None

Signed-off-by: mahanteshchitt <mahantesh_chittapur@comcast.com>

cherry-picking 98af9aa

cherry-picked ca1d844

cherry picked 348db62

RDKBWIFI-409 : [TDK][AUTO] Controller/Extender Radio DataElements Partially Missing and Incorrect in Latest EM Build

Reason for change: Moved nvram to different partitions. This partition
will be created during run-time . So, need to remove build time nvram changes
Test Procedure: Build successful and able to load the TR-181 DM
Risks: Low

Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>

cherry-picking c9ab2ed

RDKBACCL-1773: Intermittently facing build error in jenkins vm for linux-mt76

Reason for change: Installing header files from mac80211 before mt76 compiles
Test procedure: Build should be successful
Risks: None

Signed-off-by: ap934 <akhil_p@comcast.com>

cherry-picked 6e85989

cherry pickinh the commit 0c2419c

cherry pickinh the commit 5c4f4f0

cherry pickinh the commit 9b65157

RDKBACCL-1771: BPI doesnt get IPv4 from docsis gateway

Reason for change: Removing unwanted tag options
Test procedure: TBD
Risks: Low

Signed-off-by: Manigandan Gopalakrishnan <Manigandan_Gopalakrishnan@comcast.com>

RDKBACCL-1790: New rdm-agent import change is not building

Reason for change: Currently we don't have full support on rdm, removed the la libraries which are not builded.
Test Procedure: Build should succeed and sanity should pass for reference platform.
Risks: Low

Signed-off-by: ap934 <akhil_p@comcast.com>

cherry pickinh the commit af9c315

cherry pickinh the commit fb5a05d

RDKBACCL-1826 : Introduce the MP4.3 selection in source for kernel6-12 in MP4.2 workspace

Reason for change: Made changes for source to pick the MP4.3 based on machine command
Test procedure : bitbake rdk-generic-broadband-image
Risks: Low

Signed-off-by: ssiras826 <sandhyarani_sirasanagandla@comcast.com>

cherry-picked 6e85989

cherry-picked 736e218

RDKBACCL-1667 : DAC is not working in kernel6-12 new configurations are
required for mem and cpu controllers

Signed-off-by: ssiras826 <sandhyarani_sirasanagandla@comcast.com>

cherry-picked 25f0b18

cherry-picked b01056b

cherrry-picked 8a9bad4

Potential fix for pull request finding

Co-authored-by: Copilot Autofix powered by AI <175728472+Copilot@users.noreply.github.com>

cherrry-picked 4bf7401

RDKBACCL-1608: [TDK][AUTO][BPI][DML]Device.WiFi.NeighboringWiFiDiagnostic.DiagnosticsState is empty

Reason for Change: Updating the DiagnosticsState default value as 'None' as it's empty before.
Test procedure: DiagnosState value should be shown as 'None' by default.
None: Low.

Signed-off-by: ksaipr036 <kosika_saipriya@comcast.com>

cherrry-picked 2016516

RDKBACCL-1755: Remove WanManager dependency from EthAgent service

Reason for Change:
1.Avoid a circular dependency between EthAgent and WanManager.
2.At runtime, the cr-deviceprofile.xml already establishes the required dependency on EthAgent from WanManager.
3.Removing RdkWanManager.service from CcspEthAgent.service prevents the circular dependency during service startup.
Test Procedure: Sanity validation passed for both WiFiAgent and OneWifi.
Risks: None

Signed-off-by: ksaipr036 <kosika_saipriya@comcast.com>

cherry-picking 71ee585

Update ubus LICENSE to LGPL-2.1-or-later

LGPL-2.1-or-later is the license of the ubus component, not BSD.
See https://openwrt.org/docs/techref/ubus
The code is published under LGPL 2.1 license

RDKBACCL-1916 : Removed unused systemd services and psm package from

Extender
Reason for change: Below systemd services are unused in extender,
CcspEthAgent.service         loaded failed failed CcspEthAgent service
* CcspLMLite.service           loaded failed failed CcspLMLite service
* CcspTr069PaSsp.service       loaded failed failed CcspTr069PaSsp service
* dnsmasq.service              loaded failed failed DNS forwarder and DHCP server
* RdkFwUpgradeManager.service  loaded failed failed Firmware Upgrade Manager service
* RdkTelcoVoiceManager.service loaded failed failed RdkTelcoVoiceManager service
* RdkVlanManager.service       loaded failed failed RDK VlanManager service
* RdkWanManager.service        loaded failed failed Rdk Wan Manager service
* webconfig.service            loaded failed failed webconfig service
so, removed these files from Extender rootfs execution
Test Procedure: Build successful and validated the EM functionality .
Test results are updated in JIRA
Risks: Low

Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>

RDKB-62554: Provide implementation for Banana Pi STA MLO connection

Impacted Platforms:
Banana Pi

Reason for change: To make it possible for Banana Pi to make
STA MLO connection

Test Procedure: Build extender image for Banana Pi, modify
/nvram/EasymeshCfg.json and reboot the device,
verify that MLO connection was established

Risks: None

Priority: P1

Signed-off-by:Pavlo_Uvarov@comcast.com

cherry-picked 16b6e10

cherry-picked 8c4d192

cherry-picked c0e918b

RDKBACCL-1905: Align bridge-mode handlers for bridged wan interface approach

Reason for change: Linking both WAN and LAN bridges
Test procedure: Checked bridgemode functionality and SSH to erouter0 IP
Risks: Low
Priority: P0

Signed-off-by: Manigandan Gopalakrishnan <Manigandan_Gopalakrishnan@comcast.com>

cherry-picked a419544

cherry-picked 0fbb39a

cherry-picked 05eec38

cherry-picked 4ed9f7a

Update sysint-broadband.bbappend

RDKBACCL-1956: [WiFiagent] Intermittently, WiFi SSIDs are greyed out on WebUI & SSIDs not updated to default value after Factory Reset

Reason for change: When FactoryResetSSID is set to 1 during boot, execution is redirected to the wifi_factoryReset() API.
                   Restored the hostapd restart call to ensure the factory reset flow completes correctly and the default SSIDs are applied.
Test Procedure: Perform a FactoryReset.
                Verify that the default SSIDs are restored successfully after the device boots.
Risks: Low.

Signed-off-by: ksaipr036 <kosika_saipriya@comcast.com>

cherry-picked a1bc596

Change script installation paths in sysint-broadband

Updated installation paths for scripts in sysint-broadband.bbappend.

cherry-picked 09907b2

Update sysint-broadband.bbappend

RDKBACCL-1971 : Distro flag to build wifi components from AutoREV for easymesh gateway and extender builds

Reason for change : EasyMesh distro is not enabling if we used the same name for 2 comparsion
Test Procedure: Build successful with below command
MACHINE=bananapi4-rdk-broadband FEATURE_TYPE=EasyMesh ci_Staged_AUTOREV_Validation_Enabled=yes source meta-cmf-bananapi/setup-environment-refboard-rdkb
Risks: Low

Signed-off-by: Keerthana Pandurangan <keerthana_pandurangan@comcast.com>

cherry-picked c231832

cherry-picked 6076644

cherry picked 4c69cc5

RDKBACCL-2025 - Observing build issues in q2 release builds if we disable the "generic_mlo" distro feature

Reason for change : Below errors are seen,
./git/src/../platform/banana-pi/platform.c: In function 'platform_pre_create_vap': ../git/src/../platform/banana-pi/platform.c:675:12: error: invalid storage class for function 'get_sta_list_handler'
675 | static int get_sta_list_handler(struct nl_msg *msg, void *arg)
| ^~~~~~~~~~~~~~~~~~~~
../git/src/../platform/banana-pi/platform.c:698:12: error: invalid storage class for function 'get_sta_list'
698 | static int get_sta_list(wifi_interface_info_t *interface, sta_list_t *sta_list)
| ^~~~~~~~~~~~
../git/src/../platform/banana-pi/platform.c:718:13: error: invalid storage class for function 'set_wifi_standard_from_rate'
718 | static void set_wifi_standard_from_rate(struct nlattr **rate, char *cli_OperatingStandard)
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../git/src/../platform/banana-pi/platform.c:736:12: error: invalid storage class for function 'get_sta_stats_handler'
736 | static int get_sta_stats_handler(struct nl_msg *msg, void *arg)
| ^~~~~~~~~~~~~~~~~~~~~
../git/src/../platform/banana-pi/platform.c:839:12: error: invalid storage class for function 'get_sta_stats'
839 | static int get_sta_stats(wifi_interface_info_t *interface, mac_address_t mac, wifi_associated_dev3_t *dev)
| ^~~~~~~~~~~~~
../git/src/../platform/banana-pi/platform.c:1037:1: error: expected declaration or statement at end of input
1037 | }
| ^
Test Procedure: Build successful
Risks: Low

Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>

cherry picked c7f75a8

cherry picked b06b3cf

RDKBACCL-2099 : Observing build issues in latest wifiagent builds

Reason for change: Added fix for below issue
ERROR: hal-wifi-mt76-6.1+gitAUTOINC+e0fded2dff-r0 do_populate_lic: QA Issue: hal-wifi-mt76: LIC_FILES_CHKSUM points to an invalid file: /home/jenkins/jenkinsroot/workspace/build-bpi-r4-broadband-wifiagent/EXEC_0/build-bananapi4-rdk-broadband/tmp/work/cortexa53-rdk-linux/hal-wifi-mt76/6.1+gitAUTOINC+e0fded2dff-r0/git/src/wifi/../../LICENSE [license-checksum]
2026-08-23 13:08:04.877  ERROR: hal-wifi-mt76-6.1+gitAUTOINC+e0fded2dff-r0 do_populate_lic: Fatal QA errors were found, failing task.
2026-08-23 13:08:04.889  ERROR: Logfile of failure stored in: /home/jenkins/jenkinsroot/workspace/build-bpi-r4-broadband-wifiagent/EXEC_0/build-bananapi4-rdk-broadband/tmp/work/cortexa53-rdk-linux/hal-wifi-mt76/6.1+gitAUTOINC+e0fded2dff-r0/temp/log.do_populate_lic.904239
2026-08-23 13:08:04.889  NOTE: recipe hal-wifi-mt76-6.1+gitAUTOINC+e0fded2dff-r0: task do_populate_lic: Failed
Test Procedure: Build successful
Test results are updated in JIRA
Risks: Low

Signed-off-by: Keerthana Pandurangan <keerthana_pandurangan@comcast.com>

RDKBACCL-1825: Facing build error in latest BPI RDKB image

Reason For Change: Observing hunk failure in patch file Add_ipv6_changes.patch, some change got merged in generic code, hence removing it from patch file
Test Procedure: Build should be successful and functionality should work.
Risks: None

Signed-off-by: ap934 <Akhil_P@comcast.com>