RDKBACCL-867: brlan0 not getting ip when switched from bridge mode to router mode in Bananapi
Reason for change: Aligning to latest code. Removing workaround fix.
Test procedure: Tested the transition between bridgemode and routermode.
Risks: None

Signed-off-by: Manigandan Gopalakrishnan <Manigandan_Gopalakrishnan@comcast.com>

Revert "RDKBACCL-1755: Remove WanManager dependency from EthAgent service"

This reverts commit b5232df5d3cce9447c52ea0f2c0fb7fd1d8a4eb5.

RDKBACCL-2002 : Kirkstone build is breaking with otbr-agent fetcher issues

Reason for change : Added fix for the below issue
Error downloading object: app/bluetooth/common/cbap_lib/lib/cbap_CM33_gcc.a (6e32534): Smudge error: Error downloading app/bluetooth/common/cbap_lib/lib/cbap_CM33_gcc.a (6e32534bddd88d76e8e43196ac2c33f1761bbada60771a83673148098288f429): batch response: Repository or object not found: https://artifacts.silabs.net/artifactory/api/lfs/gsdk/objects/batch
Check that it exists and that you have proper access to itErrors logged to
Test Procedure: Build successful
Risks : Low

Signed-off-by: Keerthana Pandurangan <keerthana_pandurangan@comcast.com>

RDKBACCL-1499 - Missing packages/recipes in common meta-layers to support EasyMesh integration

Reason for change : Moved go recipes and related files from cmf-bananapi
layer to cmf-broadband layer.
so, deleted these files from cmf-bananapi layer
Test Procedure: Build successful
Risks: Low

Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>

RDKBACCL-1499 - Missing packages/recipes in common meta-layers to support EasyMesh integration

Reason for change : Moved EasyMesh integration changes from cmf-bananapi
layer to cmf-broadband layer
Test Procedure: Build successful and attached the test results in JIRA
Risks: Low

Signed-off-by: Keerthana Pandurangan <keerthana_pandurangan@comcast.com>

RDKBACCL-1935: Minimalize the kernel modules for BPI-R4 extender build

Reason for Change: Remove kernel modules that are not required for the extender build to optimize kernel configuration.
Test Procedure: Verify that the basic EasyMesh(EM) functionality works as expected.
Risks: None

Signed-off-by: ksaipr036 <kosika_saipriya@comcast.com>

Update srcrev for hal-fwupgrade

Signed-off-by: ap934 <Akhil_P@comcast.com>

RDKBWIFI-407 - [Easymesh] Easymesh web gui is not accessible

Reason for change : Moved rdkbcli Web gui changes from cmf-bananapi layer to cmf-broadband layer
Test Procedure: Build successful and able to launch cli in UI
Risks: Low

Signed-off-by: Keerthana Pandurangan <keerthana_pandurangan@comcast.com>

RDKBACCL-2030 - Observing build issues from BuildFromTip distro enabled builds

Reason for change : Below are the errors,
/home/jenkins/jenkinsroot/workspace/keerthana/Ctrl/Aug12/build-bananapi4-rdk-broadband/tmp/work/cortexa53-rdk-linux/ccsp-one-wifi/6.1+gitAUTOINC+067b885d3a-r0/temp/run.do_install.3735737:179 exit 1 from 'install -m 755 /home/jenkins/jenkinsroot/workspace/keerthana/Ctrl/Aug12/build-bananapi4-rdk-broadband/tmp/work/cortexa53-rdk-linux/ccsp-one-wifi/6.1+gitAUTOINC+067b885d3a-r0/git/scripts/mesh_aclmac.sh -t /home/jenkins/jenkinsroot/workspace/keerthana/Ctrl/Aug12/build-bananapi4-rdk-broadband/tmp/work/cortexa53-rdk-linux/ccsp-one-wifi/6.1+gitAUTOINC+067b885d3a-r0/image/usr/ccsp/wifi'
Also, this is temporary fix and solution of this issue is already addressed by onewifi team in comcast gerrit in meta-rdk-broadband layer.
this changes needs to be reverted once those changes are merged in cmf gerrit.
Test Procedure: Build successful
Risks: Low

Signed-off-by: Keerthana Pandurangan <keerthana_pandurangan@comcast.com>

RDKBACCL-2006: WiFi Clients are not working after device reboot in LTE and RNDIS mode

Reason for Change: WiFi interfaces were getting removed from the bridge in LTE mode due to an missing WiFi interface list in PSM.
Test Procedure: Verify that WiFi clients work correctly after device reboot in LTE/RNDIS and Gateway modes.
Risk: None.

Signed-off-by: ksaipr036 <kosika_saipriya@comcast.com>

RDKBACCL-2088 - Observing parser issues in latest kirkstone builds

Reason for change : Updated required recipes from git01 to github repo
to resolve the parser errors.
Added fix for wifiagent builds as well.
Test Procedure: Build successful
Risks: Low

Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>

RDKBACCL-2099 : Observing build issues in latest wifiagent builds

Reason for change: Added fix for below issue
ERROR: hal-wifi-mt76-6.1+gitAUTOINC+e0fded2dff-r0 do_populate_lic: QA Issue: hal-wifi-mt76: LIC_FILES_CHKSUM points to an invalid file: /home/jenkins/jenkinsroot/workspace/build-bpi-r4-broadband-wifiagent/EXEC_0/build-bananapi4-rdk-broadband/tmp/work/cortexa53-rdk-linux/hal-wifi-mt76/6.1+gitAUTOINC+e0fded2dff-r0/git/src/wifi/../../LICENSE [license-checksum]
2026-08-23 13:08:04.877  ERROR: hal-wifi-mt76-6.1+gitAUTOINC+e0fded2dff-r0 do_populate_lic: Fatal QA errors were found, failing task.
2026-08-23 13:08:04.889  ERROR: Logfile of failure stored in: /home/jenkins/jenkinsroot/workspace/build-bpi-r4-broadband-wifiagent/EXEC_0/build-bananapi4-rdk-broadband/tmp/work/cortexa53-rdk-linux/hal-wifi-mt76/6.1+gitAUTOINC+e0fded2dff-r0/temp/log.do_populate_lic.904239
2026-08-23 13:08:04.889  NOTE: recipe hal-wifi-mt76-6.1+gitAUTOINC+e0fded2dff-r0: task do_populate_lic: Failed
Test Procedure: Build successful
Test results are updated in JIRA
Risks: Low

Signed-off-by: Keerthana Pandurangan <keerthana_pandurangan@comcast.com>

RDKBACCL-2006: WiFi Clients are not working after device reboot in LTE and RNDIS mode

Reason for Change: WiFi interfaces were getting removed from the bridge in LTE mode due to an missing WiFi interface list in PSM.
Test Procedure: Verify that WiFi clients work correctly after device reboot in LTE/RNDIS and Gateway modes.
Risk: None.

Signed-off-by: ksaipr036 <kosika_saipriya@comcast.com>

Update bbhm_def_cfg_banana.xml

RDKBACCL-1975 Observing build error for Kernel 6.12 builds

Reason for change: Introducing a flag DHOSTAPD_211_v6 to address build issues against latest revision of hostapd-2.11 from MP.4.3
Test Procedure: Test the wifi sanity
Risks: Low
Priority: P1

Signed-off-by: ssiras826 <ssiras826@cable.comcast.com>

RDKBACCL-1975 Observing build error for Kernel 6.12 builds

Reason for change: Aligning the flag properly to HOSTAPD_211_V6
Test Procedure: Build pass
Risks: Low
Priority: P1

Signed-off-by: ssiras826 <ssiras826@cable.comcast.com>

RDKBACCL-1318: iPhone usb-tethering support

Reason for change: Bringing iphone usb-tethering support
Test procedure: BPI should get internet internet feed through eth0
Risks: Low

Signed-off-by: Manigandan Gopalakrishnan <Manigandan_Gopalakrishnan@comcast.com>

RDKBACCL-2061-[TDK][AUTO][BPI] selfheal_aggressive.sh Process Not Running in 26Q2 Build – SelfHealAggressive.txt Log File Not Generated
 
Reason for change:
boot_mode.sh was introduced as part of the selfheal cron/process mode
framework and is sourced by selfheal_aggressive.sh. However, it was
not installed into /usr/ccsp/tad for Bananapi builds.
 
Test Procedure:
1. perform factory-reset and wait for the device to come up
2. Check if the selfheal_aggressive.sh process is running using "ps | grep selfheal" inside the /rdklogs/logs directory
3. give ls cmd in the /rdklogs/logs directory and see if selfheal_aggressive.txt is generated
 
Risks:
Low

Signed-off-by: ajayas415_comcast <Auruthra_Jayashree@comcast.com>

RDKBACCL-2135 : observing build issues in latest tip (i,e sep7th) easymesh enabled builds

Reason for change: Added fix for below errors,
/home/jenkins/jenkinsroot/workspace/build-bpi-r4-easymesh-controller-buildfromtip/EXEC_0/build-bananapi4-rdk-broadband/tmp/work/cortexa53-rdk-linux/ccsp-one-wifi/6.1+gitAUTOINC+8a387f6cf1-r0/recipe-sysroot-native/usr/bin/aarch64-rdk-linux/../../libexec/aarch64-rdk-linux/gcc/aarch64-rdk-linux/11.3.0/ld:
cannot find -lwifi_math_utils: No such file or directory
11:11:20 | collect2: error: ld returned 1 exit status
Test Procedure: Build successful
Risks: Low

Signed-off-by: Keerthana Pandurangan <keerthana_pandurangan@comcast.com>

 RDKB-66764, RDKB-66765, RDKB-66766 - Wi-Fi Experience Index feature.

     Reason for change: Adding libwifi_quality_manager specific to Bananapi
     Test Procedure: Build compilation success

     Risks: Low

     Signed-off-by:pavanisireeshareddy_kareti@comcast.com

RDKBACCL-2149 : Tip update (i,e Sep 15th)

Reason for change: updated srcrev for uwm and dependent components recipes.
Test Procedure: Build successful and validated the EM functionality .
Test results are updated in JIRA
Risks: Low

Signed-off-by: Keerthana Pandurangan <keerthana_pandurangan@comcast.com>

rdk-wifi-libhostap: Enable EASY_MESH_NODE build flag

-Add the EASY_MESH_NODE compiler flag to rdk-wifi-libhostap for
 Banana Pi R4 builds.

-This aligns libhostapd with other EasyMesh-enabled components such
 as OneWiFi, unified-wifi-mesh, and rdk-wifi-hal

-Required to support ACL rejection status code 33 in authentication responses
 for EasyMesh builds, while preserving the existing status code 1
 behavior for non-EasyMesh builds.

Signed-off-by: Sundram Patel <sundram.p@tataelxsi.co.in>

RDKBACCL-2149 : Tip update (i,e Sep 15th)

Reason for change: updated srcrev for uwm and dependent components recipes.
Test Procedure: Build successful and validated the EM functionality .
Test results are updated in JIRA
Risks: Low

Signed-off-by: Keerthana Pandurangan <keerthana_pandurangan@comcast.com>

RDKBACCL-2143: [Onewifi]SSID not broadcasting

Reason for change: this -DCONFIG_MBO flag should not be removed, since hal and hostapd has interdependent on this flag
Test Procedure: Test all wifi functionalities
Risks: None

Signed-off-by: ssiras826 <sandhyarani_sirasanagandla@comcast.com>

RDKBACCL-2178: [TDK][AUTO][BPI][WiFiAgent] Facing build issues in latest builds

Reason for Change: Updated the patch hunk to align with the latest code changes and resolve the hunk failure during the build.
Test Procedure: hal-wifi-mt76 cimpilation should be successful and Build should be completed. Sanity should work.
Risks: Low.
Priority: P0

Signed-off-by: ksaipr036 <kosika_saipriya@comcast.com>

RDKBACCL-2180: New rdm-agent import change is not building

Reason for Change: Removed the rdm/* \ line to align with the new RDM import line and correctly terminate the list in rdm recipe.
Test Procedure: Build should pass and Sanity should be verified.
Risks: High.
Priority: P1

Signed-off-by: ksaipr036 <kosika_saipriya@comcast.com>

Update 6g_dml_mapping.patch