RDKBACCL-2099 : Observing build issues in latest wifiagent builds
Reason for change: Added fix for below issue
ERROR: hal-wifi-mt76-6.1+gitAUTOINC+e0fded2dff-r0 do_populate_lic: QA Issue: hal-wifi-mt76: LIC_FILES_CHKSUM points to an invalid file: /home/jenkins/jenkinsroot/workspace/build-bpi-r4-broadband-wifiagent/EXEC_0/build-bananapi4-rdk-broadband/tmp/work/cortexa53-rdk-linux/hal-wifi-mt76/6.1+gitAUTOINC+e0fded2dff-r0/git/src/wifi/../../LICENSE [license-checksum]
2026-08-23 13:08:04.877  ERROR: hal-wifi-mt76-6.1+gitAUTOINC+e0fded2dff-r0 do_populate_lic: Fatal QA errors were found, failing task.
2026-08-23 13:08:04.889  ERROR: Logfile of failure stored in: /home/jenkins/jenkinsroot/workspace/build-bpi-r4-broadband-wifiagent/EXEC_0/build-bananapi4-rdk-broadband/tmp/work/cortexa53-rdk-linux/hal-wifi-mt76/6.1+gitAUTOINC+e0fded2dff-r0/temp/log.do_populate_lic.904239
2026-08-23 13:08:04.889  NOTE: recipe hal-wifi-mt76-6.1+gitAUTOINC+e0fded2dff-r0: task do_populate_lic: Failed
Test Procedure: Build successful
Test results are updated in JIRA
Risks: Low

Signed-off-by: Keerthana Pandurangan <keerthana_pandurangan@comcast.com>