RDKBACCL-1909 Remove meta-rdk-opensync from Bpi builds
Reason for change: meta-rdk-opensync is no longer in use and should be removed.
Updating BBMASK to mask the whole layer, plus
fixing inconsistent license information in the ubus recipe, causing this error
ERROR: ubus-gitAUTOINC+5952b48e25-r0 do_create_spdx: Cannot find any text for license BSD
Replacing BSD with BSD-3-Clause
Test Procedure: Build successful
Risks: Low

Signed-off-by: Simon Chung <simon.chung@rdkcentral.com>