RDKBACCL-435 : Latest BPI4 build is breaking due to latest import halinterface change
Reason for change:  observing below errors,
./git/src/fwupgrade/fwupgrade_hal.c:30:10: fatal error: fwupgrade_hal.h: No such file or directory
|    30 | #include "fwupgrade_hal.h"
This issue is happening due to this gerrit changes (RDKB-56665)
Test Procedure: bitbake hal-fwupgrade
Risks: Low

Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>